### ISSUE TITLE
Could not build PDF

### ISSUE THREAD

**Issue by ribose-jeffreylau** [riboseinc/metanorma#27]
## Steps to reproduce

Given the following files living in the same directory:

**Gemfile**

```ruby
source "https://rubygems.org"

gem "metanorma", git: "https://github.com/riboseinc/metanorma"
gem "metanorma-cli", git: "https://github.com/riboseinc/metanorma-cli"
gem "metanorma-csd", git: "https://github.com/riboseinc/metanorma-csd"
```

**test.adoc**

```asciidoc
= Test doc
:title: Test doc
:docnumber: TD 1
:status: working-draft
:doctype: standard
:edition: 1
:copyright-year: 1970
:revdate: 1970-01-01T00:00:00Z
:language: en
:technical-committee: TEST
:draft:
:toc:

.Foreword
This is a test.
This is only a test.
This document was prepared by Technical Committee _{technical-committee}_.


:sectnums!:
== Introduction

This is a test.
This is only a test.

=== Definition

This is a test.
This is only a test.

:sectnums:
== Scope

This is a test.
This is only a test.


[bibliography]
== Normative References

This is a test.
This is only a test.

== Terms, definitions and abbreviations

=== Terms and definitions

Test


[[term-test]]
==== lorem

ipsum

== Conclusion

test


[[AnnexA]]
[appendix,obligation=informative]
== Technical information

=== This is only a

test.

[bibliography]
== Bibliography

* [[[ISO27000,ISO/IEC 27000:2018]]], _Information technology -- Security techniques -- Information security management systems -- Overview and vocabulary_
```

## Actual result

```console
> bundle exec metanorma -t csd -x html,pdf test.adoc 
...
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'puppeteer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/localuser/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/bundler/gems/metanorma-f272ee15004f/bin/metanorma-pdf.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

and no PDF files are produced.

## Expected result

PDF files are generated with no errors regarding '`puppeteer`'.

**Comment by ribose-jeffreylau** [comment]
## Related

On my local macOS, tests are failing:

```console
$ bundle exec rake spec
/Users/localuser/.rbenv/versions/2.4.4/bin/ruby -I/Users/localuser/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.0/lib:/Users/localuser/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-support-3.8.0/lib /Users/localuser/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

Metanorma::Output::Pdf
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'puppeteer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/localuser/share/src/metanorma/bin/metanorma-pdf.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
  generates a PDF (FAILED - 1)

Metanorma::Registry
[metanorma] processor "new" registered
  has a registry
  warns when registered class is not a Metanorma processor

Failures:

  1) Metanorma::Output::Pdf generates a PDF
     Failure/Error: expect(File.exist?("a.pdf")).to be true

       expected true
            got false
     # ./spec/output_spec.rb:10:in `block (2 levels) in <top (required)>'

Finished in 0.28262 seconds (files took 0.24132 seconds to load)
3 examples, 1 failure

Failed examples:

rspec ./spec/output_spec.rb:5 # Metanorma::Output::Pdf generates a PDF

/Users/localuser/.rbenv/versions/2.4.4/bin/ruby -I/Users/localuser/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.0/lib:/Users/localuser/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-support-3.8.0/lib /Users/localuser/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

**Comment by ronaldtse** [comment]
As described in the error, “puppeteer” is not installed. Puppeteer is the Google Chrome headless driver installed via NodeJS.

PDF generation functionality is dependent on it; please install it according to instructions.

**Comment by ribose-jeffreylau** [comment]
Here's the result after following the instructions:

```console
> bash <(curl -s https://raw.githubusercontent.com/riboseinc/metanorma-macos-setup/master/metanorma-setup)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7216  100  7216    0     0   147k      0 --:--:-- --:--:-- --:--:--  146k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   110  100   110    0     0   3102      0 --:--:-- --:--:-- --:--:--  3142

Homebrew already installed. Skipping ...

Updating Homebrew...
Already up-to-date.

Verifying the Homebrew installation...
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/localuser/.rbenv/shims/passenger-config

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  dirmngr
  gpg-agent
  docker-compose
  gnupg

Your Homebrew installation reported some errors or warnings.
If the warnings are related to Python, you can ignore them.
Otherwise, review the Homebrew messages to see if any action is needed.

Installing formulas and casks from the Brewfile ...
Using git
Using libgit2
Using plantuml
Installing sublime-text
Installing java
Homebrew Bundle complete! 5 Brewfile dependencies now installed.

All formulas and casks were installed successfully.

[node] Checking on Node.js installation...


[node] We recommend you uninstall brew's Node and re-install Node through nvm.
[node] You can re-run this script after uninstalling brew's Node to automatically install nvm.


[node: puppeteer] Puppeteer already installed.

[node] ...Finished Node.js installation checks.

[java] Checking on Java installation...

[java] Java is already installed.

[ruby] Checking on Ruby installation...

[ruby] We recommend chruby and ruby-install over RVM or rbenv

[ruby] Updating Rubygems...
Latest version already installed. Done.
bundler (1.16.5, 1.16.4, default: 1.16.2)

Updating bundler ...
Updating installed gems
Nothing to update

[ruby] Configuring Bundler ...
Your application has set jobs to "7". This will override the global value you are currently setting

[ruby] ...Finished Ruby installation checks.

[metanorma] Installing/Updating the `metanorma` gem...
metanorma (0.2.9, 0.2.8, 0.2.5)

Updating metanorma ...
Updating installed gems
Nothing to update

[metanorma-setup] Completed -- please re-launch Terminal!
> bash
> bundle exec rake
/Users/localuser/.rbenv/versions/2.4.4/bin/ruby -I/Users/localuser/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.0/lib:/Users/localuser/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-support-3.8.0/lib /Users/localuser/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

Metanorma::Output::Pdf
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'puppeteer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/localuser/share/src/metanorma/bin/metanorma-pdf.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
  generates a PDF (FAILED - 1)

Metanorma::Registry
[metanorma] processor "new" registered
  has a registry
  warns when registered class is not a Metanorma processor

Failures:

  1) Metanorma::Output::Pdf generates a PDF
     Failure/Error: expect(File.exist?("a.pdf")).to be true

       expected true
            got false
     # ./spec/output_spec.rb:10:in `block (2 levels) in <top (required)>'

Finished in 0.28944 seconds (files took 0.14258 seconds to load)
3 examples, 1 failure

Failed examples:

rspec ./spec/output_spec.rb:5 # Metanorma::Output::Pdf generates a PDF

/Users/localuser/.rbenv/versions/2.4.4/bin/ruby -I/Users/localuser/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.0/lib:/Users/localuser/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-support-3.8.0/lib /Users/localuser/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed

```

Check for 'puppeteer', using the same check from https://github.com/riboseinc/metanorma-macos-setup/blob/edc586ed7e45584883ea2e1be9fb84fbdeec2d93/mac#L176:

```console
$ npm list -g --depth 1 puppeteer
/usr/local/lib
└─┬ decktape@2.8.3
  └── puppeteer@1.4.0
```

**Comment by ribose-jeffreylau** [comment]
Installation process now works properly, via https://github.com/riboseinc/metanorma-macos-setup/pull/4 .

Closing this.

**Comment by ronaldtse** [comment]
Thanks @ribose-jeffreylau !
